site_name: Datacenter as a Computer, 4th Edition
nav:
  - Home: index.md
  - About: about.md
  - 1장. 서론: 978-3-031-99489-0_1.md
  - 2장. WSC 아키텍처 개요: 978-3-031-99489-0_2.md
  - 3장. WSC 워크로드 개요: 978-3-031-99489-0_3.md
  - 4장. WSC 소프트웨어: 978-3-031-99489-0_4.md
  - 5장. WSC 하드웨어: 978-3-031-99489-0_5.md
  - 6장. 컴퓨팅 구성 요소: 978-3-031-99489-0_6.md
  - 7장. 소프트웨어 정의 인프라: 978-3-031-99489-0_7.md
  - 8장. 성능과 비용: 978-3-031-99489-0_8.md
  - 9장. 에너지와 지속 가능성: 978-3-031-99489-0_9.md
  - 10장. 신뢰할 수 있는 컴퓨팅: 978-3-031-99489-0_10.md
  - 11장. 25년간의 WSC 여정: 978-3-031-99489-0_11.md
  - 12장. WSC 25년을 위한 엄선된 25편의 주요 논문: 978-3-031-99489-0_12.md
theme: readthedocs
